### ISSUE TITLE
About Supporting Model Path and OCR

### ISSUE THREAD

**Issue by ghada-soliman** [JosefAlbers/Phi-3-Vision-MLX#4]
Hello,

Many thanks for sharing Phi-3 Vision for Mac OS.

I would like to ask about the following:
1) Is it possible to add the model path to generate function?
2) We tested the model to extract text from the image but the extraction was not good. May you please advise about how it is tested for the extraction of the text as is from the image.

Thank you.

**Comment by JosefAlbers** [comment]
1. For adding the model path, you can use the `_load` and `_generate` functions instead of the `generate` function. This gives you more control over specifying the model path explicitly.
2. Microsoft has just released an updated Phi-3.5 model, and I've updated my GitHub repository accordingly. Since the reported performance improvements for this update look pretty decent, I think you might want to give it a try for your text extraction tasks.

**Comment by x4080** [comment]
@JosefAlbers is https://huggingface.co/mlx-community/Phi-3.5-vision-instruct-4bit is compatible ?
Thanks for your great work
